---
name: Release

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'Release tag'
        required: true
        default: '0.11.1'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/druid-exporter/druid-exporter:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/druid-exporter/druid-exporter:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Building Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ inputs.release-tag }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Push chart
        uses: appany/helm-oci-chart-releaser@v0.4.1
        with:
          name: chart
          repository: ${{ github.repository }}
          tag: ${{ inputs.release-tag }}
          path: helm
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          update_dependencies: 'true'
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: 'true'
          draft: 'true'
          tag: ${{ inputs.release-tag }}
          updateOnlyUnreleased: 'true'

